Added skip fortify

diff --git a/pipeline-modules/app-service/azure/rsaf-appsec.yaml b/pipeline-modules/app-service/azure/rsaf-appsec.yaml
--- a/pipeline-modules/app-service/azure/rsaf-appsec.yaml
+++ b/pipeline-modules/app-service/azure/rsaf-appsec.yaml
@@ -104,39 +104,34 @@ template: |
     - task: SonarQubeAnalyze@5
     - task: SonarQubePublish@5
     - script: |
-          scanToken=$({{scancentral}} -url $(CPI__SCAN_CONTROLLER_URL) start -bt none -upload -application {% if fortify_application_id %} {{ fortify_application_id }}{% else %}{{ applicationName }}{% endif %} -version 1.0 -b $(Build.BuildId) -uptoken $CPI__UP_TOKEN -bf *.csproj)
-          sleep 3
-          token=$( echo $scanToken |  grep -Eo 'token: [a-zA-Z0-9-]+' | cut -d' ' -f2)
-          sleep 3
-          {{scancentral}} -url $CPI__SCAN_CONTROLLER_URL retrieve -block -f worker.fpr -token $token
-          sleep 3
-          projDetails=$(curl 'https://ssc.nxplatform.io/ssc/api/v1/projects?fields=id,name,description&start=0&limit=10&orderby=name&includeInactive=false&myAssignedIssues=false') -H "accept: application/json" -H "Authorization: FortifyToken $CPI__FORTIFY_TOKEN")
-          sleep 3
-          id=$(echo $projDetails | jq ".data[] | select(.name == \"{{ applicationName }}\") | .id")
-          sleep 3
-          curl -X POST "https://ssc.nxplatform.io/ssc/api/v1/projectVersions/${id}/artifacts" -H "accept: application/json" -H "Authorization: FortifyToken $CPI__FORTIFY_TOKEN" -H "Content-Type: multipart/form-data" -F "file=@worker.fpr"
-          sleep 3
-          curl -k -X GET "https://ssc.nxplatform.io/ssc/api/v1/projectVersions/${id}/issues?start=0&limit=200&fields=friority&showhidden=false&showremoved=false&showsuppressed=false&showshortfilenames=false" -H "accept: application/json" -H "Authorization: FortifyToken $CPI__FORTIFY_TOKEN" > $(Build.BinariesDirectory)/out/output.log
-          sleep 3
-          cat $(Build.BinariesDirectory)/out/output.log
-          sleep 3
-          critical_count=$(cat $(Build.BinariesDirectory)/out/output.log | jq '.data[].friority' | grep "Critical" | wc -l)
-          sleep 3
-          if [ $critical_count -gt 0 ]; then
-            # Print an error message andset pipeline fail variable
-            echo "Error: There are 'critical' severity vulnerabilities in the code."
-            failPipeline=false
+          if [[ -z "${SKIP_FORTIFY}" ]]; then
+            echo "Skipping Fortify as requested"
+          else
+            scanToken=$({{scancentral}} -url $(CPI__SCAN_CONTROLLER_URL) start -bt none -upload -application {% if fortify_application_id %} {{ fortify_application_id }}{% else %}{{ applicationName }}{% endif %} -version 1.0 -b $(Build.BuildId) -uptoken $CPI__UP_TOKEN -bf *.csproj)
+            token=$( echo $scanToken |  grep -Eo 'token: [a-zA-Z0-9-]+' | cut -d' ' -f2)
+            {{scancentral}} -url $CPI__SCAN_CONTROLLER_URL retrieve -block -f worker.fpr -token $token
+            projDetails=$(curl 'https://ssc.nxplatform.io/ssc/api/v1/projects?fields=id,name,description&start=0&limit=10&orderby=name&includeInactive=false&myAssignedIssues=false') -H "accept: application/json" -H "Authorization: FortifyToken $CPI__FORTIFY_TOKEN")
+            id=$(echo $projDetails | jq ".data[] | select(.name == \"{{ applicationName }}\") | .id")
+            curl -X POST "https://ssc.nxplatform.io/ssc/api/v1/projectVersions/${id}/artifacts" -H "accept: application/json" -H "Authorization: FortifyToken $CPI__FORTIFY_TOKEN" -H "Content-Type: multipart/form-data" -F "file=@worker.fpr"
+            curl -k -X GET "https://ssc.nxplatform.io/ssc/api/v1/projectVersions/${id}/issues?start=0&limit=200&fields=friority&showhidden=false&showremoved=false&showsuppressed=false&showshortfilenames=false" -H "accept: application/json" -H "Authorization: FortifyToken $CPI__FORTIFY_TOKEN" > $(Build.BinariesDirectory)/out/output.log
+            cat $(Build.BinariesDirectory)/out/output.log
+            critical_count=$(cat $(Build.BinariesDirectory)/out/output.log | jq '.data[].friority' | grep "Critical" | wc -l)
+            if [ $critical_count -gt 0 ]; then
+              # Print an error message andset pipeline fail variable
+              echo "Error: There are 'critical' severity vulnerabilities in the code."
+              failPipeline=false
+            fi
+            high_count=$(cat $(Build.BinariesDirectory)/out/output.log | jq '.data[].friority' | grep "High" | wc -l)
+            if [ $high_count -gt 0 ]; then
+              # Print an error message and set pipeline fail variable
+              echo "Error: There are 'high' severity vulnerabilities in the code.."
+              failPipeline=false
+            fi
+            # Check if the pipeline fail variable is true
+            if [ $failPipeline = true ]; then
+                echo "There are $critical_count Critical and $high_count High Vulnerabilites. Therefore, failing the Build. Please fix the vulnerability and run the build again. "
+                exit 124
+            fi
+            rm -rf $(Build.BinariesDirectory)/out/output.log
           fi
-          high_count=$(cat $(Build.BinariesDirectory)/out/output.log | jq '.data[].friority' | grep "High" | wc -l)
-          if [ $high_count -gt 0 ]; then
-            # Print an error message and set pipeline fail variable
-            echo "Error: There are 'high' severity vulnerabilities in the code.."
-            failPipeline=false
-          fi
-          # Check if the pipeline fail variable is true
-          if [ $failPipeline = true ]; then
-              echo "There are $critical_count Critical and $high_count High Vulnerabilites. Therefore, failing the Build. Please fix the vulnerability and run the build again. "
-              exit 124
-          fi
-          rm -rf $(Build.BinariesDirectory)/out/output.log
       displayName: 'Run Fortify Scan'
